// MtBridge.test.mo — GENERATED by integration-kit/scripts/mt-bridge-fixtures.py from the FIN fixture set
// (integration-kit/legacy/mt-manifest.json). Do not edit: regenerate. Every fixture is read into its record,
// written back, and read again equal; the Prowide swift-core cross-parse and the XML round trips are the
// runner's (integration-kit/scripts/mt-bridge-roundtrip.py).
import Text "mo:core/Text";
import ISO "../ISO20022";
import MT "../iso/MtBridge";

func minorUnitsOf(c : Text) : ?Nat8 { switch (c) { case ("EGP" or "USD" or "EUR" or "GBP") ?2; case (_) null } };
let g = ISO.crossBorderEducationGuideline();
func versions(kind : Text) : Text { for (v in g.messageVersions.vals()) { if (v.kind == kind) return v.version }; "001.01" };
let options : MT.Options = { creationDateTime = "2026-09-12T10:00:00Z"; settlementMethod = g.settlementMethod; country = "EG"; versions };
let parties : MT.Party = { sender = "NBEGEGCX"; receiver = "CIBEEGCX" };

func roundTrip(mt : Text, iso : Text, fin : Text) {
  let d = MT.decode(Text.encodeUtf8(fin), null, options, minorUnitsOf);
  assert (d.mtType == mt);
  assert (d.iso == iso);
  switch (d.message) {
    case (#err(_)) { assert false };
    case (#ok(m)) {
      switch (MT.encode(m, mt, parties, minorUnitsOf)) {
        case (#err(_)) { assert false };
        case (#ok(written)) {
          let again = MT.decode(Text.encodeUtf8(written), null, options, minorUnitsOf);
          assert (again.mtType == mt);
          switch (again.message) { case (#ok(m2)) { assert (MT.equalMessage(m, m2)) }; case (#err(_)) { assert false } };
        };
      };
    };
  };
};

// the mapping tables name every one of the bridge's types
assert (MT.mappings().size() == 13);
for (m in MT.mappings().vals()) { assert (m.fields.size() > 3) };
// block-4-only text needs the caller's hint; the wrong hint is a typed refusal
let bare = Text.encodeUtf8("{4:\n:20:REF\n-}");
switch (MT.decode(bare, null, options, minorUnitsOf).message) { case (#err(is)) { assert (is[0].ruleId == "MT-TYPE") }; case (#ok(_)) { assert false } };
switch (MT.decode(bare, ?"MT999", options, minorUnitsOf).message) { case (#err(is)) { assert (is[0].ruleId == "MT-UNSUPPORTED") }; case (#ok(_)) { assert false } };

// mt101-1.fin
roundTrip("MT101", "pain.001", "{1:F01NBEGEGCXAXXX0000000000}{2:I101CIBEEGCXAXXXN}{4:\n:20:MT10108341419\n:28D:1/1\n:30:260915\n:21:TX1-716700\n:32B:EGP113177,27\n:50K:/EG380019000500000000263180002\nCairo Water Utility\n12 Corniche El Nil\nCairo EG\n:52A:NBEGEGCX\n:57A:CIBEEGCX\n:59:/EG800002000156789012345180002\nHousehold 1\n:70:water bill 2026-08 part 1\n:71A:SHA\n:21:TX2-125269\n:32B:EGP7927,79\n:50K:/EG380019000500000000263180002\nCairo Water Utility\n12 Corniche El Nil\nCairo EG\n:52A:NBEGEGCX\n:57A:CIBEEGCX\n:59:/EG800002000156789012345180002\nHousehold 2\n:70:water bill 2026-08 part 2\n:71A:SHA\n-}");
// mt101-2.fin
roundTrip("MT101", "pain.001", "{1:F01NBEGEGCXAXXX0000000000}{2:I101CIBEEGCXAXXXN}{4:\n:20:MT10194046123\n:28D:1/1\n:30:260915\n:21:TX1-601139\n:32B:EGP177913,76\n:50K:/EG380019000500000000263180002\nCairo Water Utility\n12 Corniche El Nil\nCairo EG\n:52A:NBEGEGCX\n:57A:CIBEEGCX\n:59:/EG800002000156789012345180002\nHousehold 1\n:70:water bill 2026-08 part 1\n:71A:SHA\n:21:TX2-872494\n:32B:EGP234065,60\n:50K:/EG380019000500000000263180002\nCairo Water Utility\n12 Corniche El Nil\nCairo EG\n:52A:NBEGEGCX\n:57A:CIBEEGCX\n:59:/EG800002000156789012345180002\nHousehold 2\n:70:water bill 2026-08 part 2\n:71A:SHA\n-}");
// mt103-1.fin
roundTrip("MT103", "pain.001", "{1:F01NBEGEGCXAXXX0000000000}{2:I103CIBEEGCXAXXXN}{3:{121:7cb4f55c-141a-421b-b1e7-da1d330c057f}}{4:\n:20:MT10310957032\n:23B:CRED\n:32A:260912EGP146853,88\n:50K:/EG380019000500000000263180002\nExample Debtor SAE\n1 Nile Corniche\nCairo EG\n:52A:NBEGEGCX\n:57A:CIBEEGCX\n:59:/EG800002000156789012345180002\nExample Creditor LLC\n10 Port Road\nAlexandria EG\n:70:Invoice INV-2026-001\n:71A:SHA\n-}");
// mt103-2.fin
roundTrip("MT103", "pain.001", "{1:F01NBEGEGCXAXXX0000000000}{2:I103CIBEEGCXAXXXN}{3:{121:106c6b4c-9796-43f3-a877-541e0e3d69d0}}{4:\n:20:MT10375675235\n:23B:CRED\n:32A:260912EGP212306,88\n:50K:/EG380019000500000000263180002\nExample Debtor SAE\n1 Nile Corniche\nCairo EG\n:52A:NBEGEGCX\n:57A:CIBEEGCX\n:59:/EG800002000156789012345180002\nExample Creditor LLC\n10 Port Road\nAlexandria EG\n:70:Invoice INV-2026-001\n:71A:SHA\n-}");
// mt104-1.fin
roundTrip("MT104", "pain.008", "{1:F01NBEGEGCXAXXX0000000000}{2:I104CIBEEGCXAXXXN}{4:\n:20:MT10472053869\n:30:260920\n:50K:/ACC66784236\nCairo Water Utility\n:52A:NBEGEGCX\n:21:COLL1-821737\n:21C:MANDATE-046880\n:23E:OTHR\n:32B:EGP473,65\n:57A:CIBEEGCX\n:59:/EG380019000500000000263180002\nHousehold 1\n:70:water bill 2026-08\n:21:COLL2-110686\n:21C:MANDATE-497359\n:23E:OTHR\n:32B:EGP461,08\n:57A:CIBEEGCX\n:59:/EG380019000500000000263180002\nHousehold 2\n:70:water bill 2026-08\n-}");
// mt104-2.fin
roundTrip("MT104", "pain.008", "{1:F01NBEGEGCXAXXX0000000000}{2:I104CIBEEGCXAXXXN}{4:\n:20:MT10420086858\n:30:260920\n:50K:/ACC30929555\nCairo Water Utility\n:52A:NBEGEGCX\n:21:COLL1-133570\n:21C:MANDATE-590984\n:23E:OTHR\n:32B:EGP118,29\n:57A:CIBEEGCX\n:59:/EG380019000500000000263180002\nHousehold 1\n:70:water bill 2026-08\n:21:COLL2-259644\n:21C:MANDATE-346107\n:23E:OTHR\n:32B:EGP175,94\n:57A:CIBEEGCX\n:59:/EG380019000500000000263180002\nHousehold 2\n:70:water bill 2026-08\n-}");
// mt202-1.fin
roundTrip("MT202", "pacs.009", "{1:F01NBEGEGCXAXXX0000000000}{2:I202DEUTDEFFAXXXN}{3:{121:1b2ec295-eca4-4e9b-9263-d7d2b852c040}}{4:\n:20:MT20242773940\n:21:REL92636216\n:32A:260912USD1889540,67\n:52A:NBEGEGCX\n:56A:CHASUS33\n:57A:DEUTDEFF\n:58A:CIBEEGCX\n:72:/INS/NBEGEGCX\n-}");
// mt202-2.fin
roundTrip("MT202", "pacs.009", "{1:F01NBEGEGCXAXXX0000000000}{2:I202DEUTDEFFAXXXN}{3:{121:0db26c50-50d7-487e-8617-ea0f1bf4f245}}{4:\n:20:MT20260624909\n:21:REL43797665\n:32A:260912USD1965097,54\n:52A:NBEGEGCX\n:56A:CHASUS33\n:57A:DEUTDEFF\n:58A:CIBEEGCX\n:72:/INS/NBEGEGCX\n-}");
// mt202cov-1.fin
roundTrip("MT202COV", "pacs.009 COV + pacs.008", "{1:F01NBEGEGCXAXXX0000000000}{2:I202DEUTDEFFAXXXN}{3:{119:COV}{121:2ba50f56-eed0-4654-8445-f7062684a112}}{4:\n:20:MT202C7751229\n:21:MT10309345837\n:32A:260912USD29213,86\n:52A:NBEGEGCX\n:57A:DEUTDEFF\n:58A:CIBEEGCX\n:50K:/EG380019000500000000263180002\nExample Debtor SAE\n1 Nile Corniche\nCairo EG\n:52A:NBEGEGCX\n:57A:CIBEEGCX\n:59:/DE89370400440532013000\nExample Creditor GmbH\n10 Market Platz\nBerlin DE\n:70:Cross-border invoice 2026-001\n:33B:USD57589,53\n-}");
// mt202cov-2.fin
roundTrip("MT202COV", "pacs.009 COV + pacs.008", "{1:F01NBEGEGCXAXXX0000000000}{2:I202DEUTDEFFAXXXN}{3:{119:COV}{121:5c8f0e6a-31ca-4318-90fa-a6fbe1cc3dcb}}{4:\n:20:MT202C1295310\n:21:MT10311575130\n:32A:260912USD12862,26\n:52A:NBEGEGCX\n:57A:DEUTDEFF\n:58A:CIBEEGCX\n:50K:/EG380019000500000000263180002\nExample Debtor SAE\n1 Nile Corniche\nCairo EG\n:52A:NBEGEGCX\n:57A:CIBEEGCX\n:59:/DE89370400440532013000\nExample Creditor GmbH\n10 Market Platz\nBerlin DE\n:70:Cross-border invoice 2026-001\n:33B:USD56065,67\n-}");
// mt900-1.fin
roundTrip("MT900", "camt.054", "{1:F01NBEGEGCXAXXX0000000000}{2:I900CIBEEGCXAXXXN}{4:\n:20:MT90005832248\n:21:REL78157283\n:25:EG380019000500000000263180002\n:32A:260912EGP131806,32\n:52A:CIBEEGCX\n:72:/UETR/fb29dd1c-102c-45da-9f4a-78a5b2b727a6\n/BNF/settlement of ACH cycle 1\n-}");
// mt900-2.fin
roundTrip("MT900", "camt.054", "{1:F01NBEGEGCXAXXX0000000000}{2:I900CIBEEGCXAXXXN}{4:\n:20:MT90013888930\n:21:REL22353657\n:25:EG380019000500000000263180002\n:32A:260912EGP170591,64\n:52A:CIBEEGCX\n:72:/UETR/56ac817d-ae1f-481a-ae62-ededc6f22e72\n/BNF/settlement of ACH cycle 1\n-}");
// mt910-1.fin
roundTrip("MT910", "camt.054", "{1:F01NBEGEGCXAXXX0000000000}{2:I910CIBEEGCXAXXXN}{4:\n:20:MT91071167908\n:21:REL28372808\n:25:EG380019000500000000263180002\n:32A:260912EGP98241,22\n:50K:Salary Payroll Ltd\n:72:/BNF/payroll September\n-}");
// mt910-2.fin
roundTrip("MT910", "camt.054", "{1:F01NBEGEGCXAXXX0000000000}{2:I910CIBEEGCXAXXXN}{4:\n:20:MT91084737524\n:21:REL58983610\n:25:EG380019000500000000263180002\n:32A:260912EGP10155,37\n:50K:Salary Payroll Ltd\n:72:/BNF/payroll September\n-}");
// mt940-1.fin
roundTrip("MT940", "camt.053", "{1:F01NBEGEGCXAXXX0000000000}{2:I940CIBEEGCXAXXXN}{4:\n:20:MT94088721810\n:25:EG380019000500000000263180002\n:28C:1/1\n:60F:C260911EGP63124,74\n:61:260912C2307,42NTRFNONREF//REF1-400369\n:86:/UETR/c751ce17-3e6a-4bdd-83dc-523910e283fa\n/NAME/Counterparty 1\nremittance line 1\n:61:260912D7370,13NTRFNONREF//REF2-509477\n:86:/UETR/6106d085-62a8-46f1-9fe7-591799258117\n/NAME/Counterparty 2\nremittance line 2\n:61:260912C5253,36NTRFNONREF//REF3-559197\n:86:/UETR/eac19320-e9e0-4c02-a5a2-b4e47a889825\n/NAME/Counterparty 3\nremittance line 3\n:62F:C260912EGP13024,22\n-}");
// mt940-2.fin
roundTrip("MT940", "camt.053", "{1:F01NBEGEGCXAXXX0000000000}{2:I940CIBEEGCXAXXXN}{4:\n:20:MT94027915048\n:25:EG380019000500000000263180002\n:28C:1/1\n:60F:C260911EGP86005,07\n:61:260912C496,80NTRFNONREF//REF1-204646\n:86:/UETR/36d96694-163d-47bf-95d6-1056984a99d9\n/NAME/Counterparty 1\nremittance line 1\n:61:260912D1331,73NTRFNONREF//REF2-065052\n:86:/UETR/f95b17fd-b47e-448d-8806-c1bfd64f81e1\n/NAME/Counterparty 2\nremittance line 2\n:61:260912C8219,29NTRFNONREF//REF3-901422\n:86:/UETR/f5e99afa-ac71-41fb-a78c-51efe0942235\n/NAME/Counterparty 3\nremittance line 3\n:62F:C260912EGP38113,85\n-}");
// mt950-1.fin
roundTrip("MT950", "camt.053", "{1:F01NBEGEGCXAXXX0000000000}{2:I950CIBEEGCXAXXXN}{4:\n:20:MT95012556156\n:25:EG380019000500000000263180002\n:28C:1/1\n:60F:C260911EGP30919,64\n:61:260912C1238,60NTRFNONREF//REF1-372208\n:61:260912D8085,86NTRFNONREF//REF2-312135\n:61:260912C4002,80NTRFNONREF//REF3-930659\n:62F:C260912EGP26278,37\n-}");
// mt950-2.fin
roundTrip("MT950", "camt.053", "{1:F01NBEGEGCXAXXX0000000000}{2:I950CIBEEGCXAXXXN}{4:\n:20:MT95023354137\n:25:EG380019000500000000263180002\n:28C:1/1\n:60F:C260911EGP53548,78\n:61:260912C4632,19NTRFNONREF//REF1-701045\n:61:260912D6757,24NTRFNONREF//REF2-302232\n:61:260912C4411,29NTRFNONREF//REF3-613241\n:62F:C260912EGP78209,38\n-}");
// mt942-1.fin
roundTrip("MT942", "camt.052", "{1:F01NBEGEGCXAXXX0000000000}{2:I942CIBEEGCXAXXXN}{4:\n:20:MT94211091620\n:25:EG380019000500000000263180002\n:28C:1/1\n:34F:EGP0,00\n:13D:2609121030+0200\n:61:260912C7332,82NTRFNONREF//INT1-910857\n:86:/UETR/8437583e-b46c-422b-9d16-1f8d4c6dbc35\n/NAME/Intraday counterparty 1\nintraday line 1\n:61:260912D7118,03NTRFNONREF//INT2-460642\n:86:/UETR/2deb4dd8-d176-4425-a3e7-3d7646469580\n/NAME/Intraday counterparty 2\nintraday line 2\n:90D:1EGP100,00\n:90C:1EGP200,00\n-}");
// mt942-2.fin
roundTrip("MT942", "camt.052", "{1:F01NBEGEGCXAXXX0000000000}{2:I942CIBEEGCXAXXXN}{4:\n:20:MT94238735312\n:25:EG380019000500000000263180002\n:28C:1/1\n:34F:EGP0,00\n:13D:2609121030+0200\n:61:260912C5069,17NTRFNONREF//INT1-073102\n:86:/UETR/ba9d7d58-20f3-4dcb-83ef-c512f888992a\n/NAME/Intraday counterparty 1\nintraday line 1\n:61:260912D7264,49NTRFNONREF//INT2-226495\n:86:/UETR/500a48fa-7d52-40d0-88bc-7d100bc48230\n/NAME/Intraday counterparty 2\nintraday line 2\n:90D:1EGP100,00\n:90C:1EGP200,00\n-}");
// mt192-1.fin
roundTrip("MT192", "camt.056", "{1:F01NBEGEGCXAXXX0000000000}{2:I192CIBEEGCXAXXXN}{4:\n:20:MT19257012567\n:21:MT10335511878\n:11S:103\n260912\n:79:/CUST/customer asked to cancel before settlement\n/ACTION/CANCEL\n/UETR/b2649db3-0713-4b70-bd3b-877e4a56d469\nplease return funds to the ordering customer\n-}");
// mt192-2.fin
roundTrip("MT192", "camt.056", "{1:F01NBEGEGCXAXXX0000000000}{2:I192CIBEEGCXAXXXN}{4:\n:20:MT19222982057\n:21:MT10354214904\n:11S:103\n260912\n:79:/CUST/customer asked to cancel before settlement\n/ACTION/CANCEL\n/UETR/a8249a64-8ad8-418d-bb50-8b49a7da4f69\nplease return funds to the ordering customer\n-}");
// mt196-1.fin
roundTrip("MT196", "camt.029", "{1:F01CIBEEGCXAXXX0000000000}{2:I196NBEGEGCXAXXXN}{4:\n:20:MT19688485559\n:21:MT19203708812\n:76:/CNCL/cancellation accepted\n/ACTION/CANCELLED\nfunds returned under our reference MT19688485559\n:11R:192\n260912\n-}");
// mt196-2.fin
roundTrip("MT196", "camt.029", "{1:F01CIBEEGCXAXXX0000000000}{2:I196NBEGEGCXAXXXN}{4:\n:20:MT19636151556\n:21:MT19240910054\n:76:/CNCL/cancellation accepted\n/ACTION/CANCELLED\nfunds returned under our reference MT19636151556\n:11R:192\n260912\n-}");
// mt199-1.fin
roundTrip("MT199", "camt.110", "{1:F01CIBEEGCXAXXX0000000000}{2:I199NBEGEGCXAXXXN}{4:\n:20:MT19993162512\n:21:MT10397198142\n:79:/INFO/beneficiary claims non-receipt\n/ACTION/INVESTIGATE\nplease confirm the value date applied\n-}");
// mt199-2.fin
roundTrip("MT199", "camt.110", "{1:F01CIBEEGCXAXXX0000000000}{2:I199NBEGEGCXAXXXN}{4:\n:20:MT19935682212\n:21:MT10327931638\n:79:/INFO/beneficiary claims non-receipt\n/ACTION/INVESTIGATE\nplease confirm the value date applied\n-}");

// 26 FIN fixtures across 13 types read, written and read again.
